### ISSUE TITLE
schedule task on new service from blueprint fails due to missing user secret in request

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-robot#191]
## Blueprint 
```
services:
  - github.com/zero-os/0-templates/node/0.0.1__e20f815a:
      redisAddr: 147.75.32.169
      hostname: myzeros
      redisPort: 6379

  - github.com/zero-os/0-templates/container/0.0.1__dfb4a473:
      flist: https://hub.gig.tech/gig-official-apps/ubuntu1604.flist
      storage: ardb://hub.gig.tech:16379
      hostname: dfb4a473

actions:
  - template: github.com/zero-os/0-templates/container/0.0.1
    actions: ['install']
```
## Error 
``` error during execution of the blueprint: you are trying to schedule action on some services on which you don't have rights. ```

**Comment by zaibon** [comment]
You blueprint is wrong.
```yaml
  - github.com/zero-os/0-templates/node/0.0.1__e20f815a:
      redisAddr: 147.75.32.169
      hostname: myzeros
      redisPort: 6379
```
This is not a valid data for a node template anymore, check https://github.com/zero-os/0-templates/tree/master/templates/node

But that is not the bug you're having.
