### ISSUE TITLE
service created in a blueprint should be cleaned up if blueprint fail to execute halfway trough

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-robot#199]
## Scenario
1- Clear data repo and start zrobot server as follows
```
zrobot server start --listen :6601 --template-repo https://github.com/openvcloud/0-templates.git --data-repo https://github.com/john-kheir/0-robot6.git
```
2- Execute this blueprint (b1)
```services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__b604910f:
       name: 'd118cf95'
       dir: '/root/.ssh/'
       passphrase: 'b604910f'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__9b5fed86:
      name: 'be-g8-3.2'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '****'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__b2cc6570:
      openvcloud: 9b5fed86
      email: 76345c4c@test.com
      groups: ['user']
      name: 51662ee9
      provider: itsyouonline
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_2:
      openvcloud: 9b5fed86
      email: dina.magdy.mohammed+123@gmail.com
      name: gig_qa_1
      provider: itsyouonline

  - github.com/openvcloud/0-templates/account/0.0.1__1b6afa12:
      openvcloud: 9b5fed86
      name: 039b220c

  - github.com/openvcloud/0-templates/vdc/0.0.1__b7e41200:
      name: 5de6f1df

actions:
  - template: github.com/openvcloud/0-templates/openvcloud/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']
```

2'- Result: "account service name is required" .. This result is expected .. Also no services have been created and accordingly no secrets which is expected as well.
```
root@0-robot0:/tmp# zrobot blueprint execute b1.yaml 
error during execution of the blueprint: account service name is required

```
```
root@0-robot0:/tmp# zrobot service list
root@0-robot0:/tmp# 

```
```
root@0-robot0:/opt/cfg/myconfig/j.clients.zrobot# cat main.toml 

jwt_ = ''

secrets_ = [ ]

url = 'http://localhost:6601'

```

3- Execute another blueprint (b2) to create 2 vdcs using different services. 
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__0f7ab843:
       name: 'a8181658'
       dir: '/root/.ssh/'
       passphrase: '0f7ab843'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__5345b873:
      name: 'be-g8-3.1'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '***'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      openvcloud: 5345b873
      email: dina.magdy.mohammed+123@gmail.com
      name: gig_qa_1
      provider: itsyouonline
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__79429c00:
      openvcloud: 5345b873
      email: 23b7b0aa@test.com
      groups: ['user']
      name: 215a1b87
      provider: itsyouonline

  - github.com/openvcloud/0-templates/account/0.0.1__d33f4790:
      openvcloud: 5345b873
      name: b5dee800

  - github.com/openvcloud/0-templates/vdc/0.0.1__873ab6db:
      account: d33f4790
      name: 96b2257f
  - github.com/openvcloud/0-templates/vdc/0.0.1__fd744b5d:
      account: d33f4790
      name: a56212c7

actions:
  - template: github.com/openvcloud/0-templates/openvcloud/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']

```

## Actual Result
I'm getting this error
My question here: for the first blueprint (b1), there are no services .. so why b2 is complaining?
even if there was services for b1 that have been created and i can't see it .. I'm still using different services for b3.
```
root@0-robot0:/tmp# zrobot blueprint execute b2.yaml 
error during execution of the blueprint: you are trying to schedule action on some services on which you don't have rights.

```
