### ISSUE TITLE
Create flist of 0-robot

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#48]
We need to be able to deploy 0-robot on top of 0-OS containers

**Comment by zaibon** [comment]
I created an flist based on the docker of 0-robot using the 0-hub feature of docker to flist conversion.
It can be found there: https://hub.gig.tech/zaibon/jumpscale-0-robot-latest.flist.md

**Comment by zaibon** [comment]
We need to automate this.
So a scrip that execute the docker build script then send a requests on the hub to convert the docker image to an flist.

**Comment by muhamadazmy** [comment]
After a quick discussion with @zaibon we agreed on the following
- On boot the zos will auto start the zrobot flist with a `toml` file like the following
```toml
[startup.zrobot]
name = "corex.create-sync"
tags = ["zrobot"] #container tags
protected = true #set protected to true to respawn the container if it crashed

[startup.zrobot.args]
root = "http://path/to/image.flist" #url of the zrobot flist
name = "zrobot"
privileged = true
host_network = true
# all other container create arguments are supported
mounts = ? # probably need something from /var/cache for persistence
``` 

- The zrobot flist must define it's own `.startup.toml` file to auto spawn the required services
  - prepare script ?
  - the actual zrobot process
  - the zrobot startup block should also be protected, to respawn if crashed

All the configuration files structured are documented [here](https://github.com/zero-os/0-core/blob/development/docs/containers/autostart.md)
